// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Entities;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(CarDBContext))]
    partial class CarDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Entities.CarLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarLetters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AK",
                            Region = "Krym"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AB",
                            Region = "Vinnitska Oblast"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AC",
                            Region = "Volynska Oblast"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AE",
                            Region = "Dnipropetrovska Oblast"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AH",
                            Region = "Donetska Oblast"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AM",
                            Region = "Shitomerska Oblast"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AO",
                            Region = "Sakarpatska Oblast"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AP",
                            Region = "Saporishka Oblast"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AT",
                            Region = "Ivano-Frankivska Oblast"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AA",
                            Region = "Kyiv"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AI",
                            Region = "Kyivska Oblast"
                        },
                        new
                        {
                            Id = 12,
                            Code = "BA",
                            Region = "Kirovogradska Oblast"
                        },
                        new
                        {
                            Id = 13,
                            Code = "BB",
                            Region = "Lyganska Oblast"
                        },
                        new
                        {
                            Id = 14,
                            Code = "BC",
                            Region = "Lvivska Oblast"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BE",
                            Region = "Mukolaivska Oblast"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BH",
                            Region = "Odeska Oblast"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BI",
                            Region = "Poltavska Oblast"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BK",
                            Region = "Rivnenska Oblast"
                        },
                        new
                        {
                            Id = 19,
                            Code = "CH",
                            Region = "Sevastopol"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BM",
                            Region = "Sumska Oblast"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BO",
                            Region = "Ternopilska Oblast"
                        },
                        new
                        {
                            Id = 22,
                            Code = "AX",
                            Region = "Harkivska Oblast"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BT",
                            Region = "Hersonska Oblast"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BX",
                            Region = "Hmelnytska Oblast"
                        },
                        new
                        {
                            Id = 25,
                            Code = "CA",
                            Region = "Cherkaska Oblast"
                        },
                        new
                        {
                            Id = 26,
                            Code = "CB",
                            Region = "Chernigivska Oblast"
                        },
                        new
                        {
                            Id = 27,
                            Code = "CE",
                            Region = "Chernivetska Oblast"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
